services:
  - type: web
    name: soundcollect
    env: static
    staticPublishPath: .
    routes:
      - type: redirect
        source: /seonamsa
        destination: /seonamsa/
        permanent: true
      - type: redirect
        source: /suncheonman
        destination: /suncheonman/
        permanent: true
